categories:
  SiteBraunfels:
    label: 'Site Default'

  SiteBraunfels.page:
    label: 'Page'
    parent: SiteBraunfels

  SiteBraunfels.navigation:
    label: 'Navigation'
    parent: SiteBraunfels

  SiteBraunfels.schemaOrg:
    label: 'Schema.org'
    parent: SiteBraunfels

  SiteBraunfels.news:
    label: 'News'
    parent: SiteBraunfels

  SiteBraunfels.greensContact:
    label: 'Greens Contact'
    parent: SiteBraunfels

settings:

  site.page.fluid.layoutRootPath:
    label: 'Page Fluid Layout Root Path'
    category: SiteBraunfels.page
    type: string
    default: 'EXT:site_braunfels/Resources/Private/Page/Layouts/'

  site.page.fluid.partialRootPath:
    label: 'Page Fluid Partial Root Path'
    category: SiteBraunfels.page
    type: string
    default: 'EXT:site_braunfels/Resources/Private/Page/Partials/'

  site.page.fluid.templateRootPath:
    label: 'Page Fluid Template Root Path'
    category: SiteBraunfels.page
    type: string
    default: 'EXT:site_braunfels/Resources/Private/Page/Templates/'

  site.page.rootPid:
    label: 'Root PID'
    category: SiteBraunfels.page
    type: int
    default: 163

  site.page.siteName:
    label: 'Site Name'
    category: SiteBraunfels.page
    type: string
    default: 'GRÜNE Braunfels'

  site.page.cssAdditions:
    label: 'Additional CSS Classes'
    category: SiteBraunfels.page
    type: string
    default: ''

  site.page.specialPages.oldBrowserPid:
    label: 'Old Browser Page PID'
    category: SiteBraunfels.page
    type: int
    default: 168

  site.page.specialPages.noScriptPid:
    label: 'NoScript Page PID'
    category: SiteBraunfels.page
    type: int
    default: 167

  site.navigation.topPid:
    label: 'Top Navigation PID'
    category: SiteBraunfels.navigation
    type: int
    default: 170

  site.navigation.footerPid:
    label: 'Footer Navigation PID'
    category: SiteBraunfels.navigation
    type: int
    default: 173

  site.navigation.mobileSearchPid:
    label: 'Mobile Search PID'
    category: SiteBraunfels.navigation
    type: int
    default: 6

  site.schemaOrg.teaserImage.width:
    label: 'Teaser image width'
    category: SiteBraunfels.schemaOrg
    type: string
    default: '600c'

  site.schemaOrg.teaserImage.height:
    label: 'Teaser image height'
    category: SiteBraunfels.schemaOrg
    type: string
    default: '600c'

  site.schemaOrg.organization.name:
    label: 'Organization Name'
    category: SiteBraunfels.schemaOrg
    type: string
    default: 'DIE GRÜNEN Baunfels'

  site.schemaOrg.sameAs:
    label: 'Schema.org sameAs URL'
    category: SiteBraunfels.schemaOrg
    type: string
    default: 'www.gruene-braunfels.de'

  site.news.startingpoint:
    label: 'Startingpoint'
    category: SiteBraunfels.news
    type: string
    default: '179,180'

  site.greensContact.pages:
    label: 'Pages'
    category: SiteBraunfels.greensContact
    type: string
    default: '178'
