categories:
  siteHerborn:
    label: 'Site Default'

  siteHerborn.page:
    label: 'Page'
    parent: siteHerborn

  siteHerborn.navigation:
    label: 'Navigation'
    parent: siteHerborn

  siteHerborn.schemaOrg:
    label: 'Schema.org'
    parent: siteHerborn

  siteHerborn.news:
    label: 'News'
    parent: siteHerborn

  siteHerborn.greensContact:
    label: 'Greens Contact'
    parent: siteHerborn

settings:

  site.page.fluid.layoutRootPath:
    label: 'Page Fluid Layout Root Path'
    category: siteHerborn.page
    type: string
    default: 'EXT:site_herborn/Resources/Private/Page/Layouts/'

  site.page.fluid.partialRootPath:
    label: 'Page Fluid Partial Root Path'
    category: siteHerborn.page
    type: string
    default: 'EXT:site_herborn/Resources/Private/Page/Partials/'

  site.page.fluid.templateRootPath:
    label: 'Page Fluid Template Root Path'
    category: siteHerborn.page
    type: string
    default: 'EXT:site_herborn/Resources/Private/Page/Templates/'

  site.page.rootPid:
    label: 'Root PID'
    category: siteHerborn.page
    type: int
    default: 32

  site.page.siteName:
    label: 'Site Name'
    category: siteHerborn.page
    type: string
    default: 'GRÜNE Herborn'

  site.page.cssAdditions:
    label: 'Additional CSS Classes'
    category: siteHerborn.page
    type: string
    default: ''

  site.page.specialPages.oldBrowserPid:
    label: 'Old Browser Page PID'
    category: siteHerborn.page
    type: int
    default: 47

  site.page.specialPages.noScriptPid:
    label: 'NoScript Page PID'
    category: siteHerborn.page
    type: int
    default: 46

  site.navigation.topPid:
    label: 'Top Navigation PID'
    category: siteHerborn.navigation
    type: int
    default: 33

  site.navigation.footerPid:
    label: 'Footer Navigation PID'
    category: siteHerborn.navigation
    type: int
    default: 34

  site.navigation.mobileSearchPid:
    label: 'Mobile Search PID'
    category: siteHerborn.navigation
    type: int
    default: 6

  site.schemaOrg.teaserImage.width:
    label: 'Teaser image width'
    category: siteHerborn.schemaOrg
    type: string
    default: '600c'

  site.schemaOrg.teaserImage.height:
    label: 'Teaser image height'
    category: siteHerborn.schemaOrg
    type: string
    default: '600c'

  site.schemaOrg.organization.name:
    label: 'Organization Name'
    category: siteHerborn.schemaOrg
    type: string
    default: 'GRÜNE Lahn-Dill'

  site.schemaOrg.sameAs:
    label: 'Schema.org sameAs URL'
    category: siteHerborn.schemaOrg
    type: string
    default: 'www.gruene-lahn-dill.de'

  site.news.startingpoint:
    label: 'Startingpoint'
    category: siteHerborn.news
    type: string
    default: '54'

  site.greensContact.pages:
    label: 'Pages'
    category: siteHerborn.greensContact
    type: string
    default: '44'
