plugin.tx_mediautils.settings.responsiveImages.showSourceViaTitle: true
ns_instagram.configuration.api.graphapi: IGAAMtVb5oVudBZAFljc1lKQjZAIdlBiOGE5VTNhT0xMeFJXNzFIS3NhMkJDa0ZAfcW5Wd0p0NGpNclg4Wmhsb1ZAvUjZAZAOGE1blBWRWVEYVRMUlI4ZAzNTdURMSkY0eTlhdmg4RWw0cjJzNlliSzFmTU9ZAV3laSVZAiVjFSeFpGSmozYwZDZD
