name: madj2k/parallax-stack
prefixType: vendor # prefixing with vendor for reuse of database fields
fields:
  - identifier: madj2k/background-color-extended
    type: Basic
  - identifier: parallax_stack_items
    type: Collection
    minitems: 1
    foreign_table: tt_content
    allowedRecordTypes:
      - madj2k_parallaxstackitem
      - madj2k_parallaxstackitemquote
    appearance:
      levelLinksPosition: both
    overrideChildTca:
      columns:
        CType:
          config:
            default: madj2k_parallaxstackitem
