name: madj2k/parallax-stack-item-quote
prefixType: vendor # prefixing with vendor for reuse of database fields
fields:
  - identifier: madj2k/quote-required
    type: Basic
  - identifier: madj2k/cite
    type: Basic
  - identifier: tab-style
    type: Tab
  - identifier: madj2k/text-orientation
    type: Basic
  - identifier: madj2k/background-color
    type: Basic
